[package]
name = "rit-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "rit"
path = "src/main.rs"

[dependencies]
rit-core = { path = "../rit-core" }

[features]
default = []
indexdb = ["rit-core/indexdb"]
large-files = ["lfs", "xet"]
lfs = ["rit-core/lfs"]
xet = ["rit-core/xet"]

[dev-dependencies]
rit-testkit = { path = "../rit-testkit" }
serde_json = "1.0.147"
